from __future__ import annotations

from typing import Protocol
from uuid import UUID

from src.domain.models.entities import (
    AgentGeneration,
    CallSessionContext,
    ToolExecution,
    Turn,
    VoiceGeneration,
)


class CallRepository(Protocol):
    async def insert(self, session: CallSessionContext) -> None: ...
    async def update_status(self, call_id: UUID, status: str, ended_at: int | None = None) -> None: ...
    async def get_by_id(self, call_id: UUID) -> CallSessionContext | None: ...


class TurnRepository(Protocol):
    async def insert(self, turn: Turn) -> None: ...
    async def update(self, turn: Turn) -> None: ...
    async def get_by_id(self, turn_id: UUID) -> Turn | None: ...
    async def list_by_call(self, call_id: UUID) -> list[Turn]: ...


class AgentGenerationRepository(Protocol):
    async def insert(self, generation: AgentGeneration) -> None: ...
    async def update(self, generation: AgentGeneration) -> None: ...
    async def get_by_id(self, agent_generation_id: UUID) -> AgentGeneration | None: ...
    async def list_by_turn(self, turn_id: UUID) -> list[AgentGeneration]: ...


class VoiceGenerationRepository(Protocol):
    async def insert(self, voice: VoiceGeneration) -> None: ...
    async def update(self, voice: VoiceGeneration) -> None: ...
    async def get_by_id(self, voice_generation_id: UUID) -> VoiceGeneration | None: ...
    async def list_by_agent_generation(self, agent_generation_id: UUID) -> list[VoiceGeneration]: ...


class ToolExecutionRepository(Protocol):
    async def insert(self, tool: ToolExecution) -> None: ...
    async def update(self, tool: ToolExecution) -> None: ...
    async def get_by_id(self, tool_request_id: UUID) -> ToolExecution | None: ...
    async def list_by_agent_generation(self, agent_generation_id: UUID) -> list[ToolExecution]: ...
